version: "3.3"

services:
  caddy:
    image: caddy:2.2.1
    restart: always
    volumes:
      - ./data:/data
      - ./config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /home/user/path/to/react/app/build:/www
    network_mode: "host"

